export default {
    card_name: "幻獣機アウローラドン",
    card_type: "モンスター" as const,
    monster_type: "リンクモンスター" as const,
    link: 3,
    linkDirection: ["左", "下", "右"] as const,
    element: "風" as const,
    race: "機械" as const,
    attack: 2100,
    filterAvailableMaterials: () => true,
    materialCondition: () => true,
    text: "機械族モンスター２体以上\n①：このカードがリンク召喚に成功した場合に発動できる。自分フィールドに「幻獣機トークン」（機械族・風・星３・攻／守０）３体を特殊召喚する。このターン、自分はリンク召喚できない。②：１ターンに１度、自分フィールドのモンスターを３体までリリースして発動できる。リリースしたモンスターの数によって以下の効果を適用する。●１体：フィールドのカード１枚を選んで破壊する。●２体：デッキから「幻獣機」モンスター１体を特殊召喚する。●３体：自分の墓地から罠カード１枚を選んで手札に加える。",
    image: "card100179342_1.jpg",
    hasDefense: false as const,
    hasLevel: false as const,
    hasLink: true as const,
    hasRank: false as const,
    canNormalSummon: false,
};
