export default {
    card_name: "神聖なる魂",
    card_type: "モンスター" as const,
    monster_type: "効果モンスター" as const,
    level: 6,
    element: "光" as const,
    race: "天使" as const,
    attack: 2000,
    defense: 1800,
    text: "このカードは通常召喚できない。自分の墓地から光属性モンスター２体を除外した場合に特殊召喚できる。(1)：このカードがモンスターゾーンに存在する限り、相手フィールドのモンスターの攻撃力は、相手バトルフェイズの間３００ダウンする。",
    image: "card100177659_1.jpg",
    hasDefense: true as const,
    hasLevel: true as const,
    hasRank: false as const,
    hasLink: false as const,
    canNormalSummon: false,
};
