export default {
    card_name: "虹光の宣告者",
    card_type: "モンスター" as const,
    monster_type: "シンクロモンスター" as const,
    level: 4,
    element: "光" as const,
    race: "天使" as const,
    attack: 600,
    defense: 1000,
    filterAvailableMaterials: () => true,
    materialCondition: () => true,
    text: "チューナー＋チューナー以外のモンスター１体以上\n(1)：このカードがモンスターゾーンに存在する限り、お互いの手札・デッキから墓地へ送られるモンスターは墓地へは行かず除外される。\n(2)：モンスターの効果・魔法・罠カードが発動した時、このカードをリリースして発動できる。その発動を無効にし破壊する。\n(3)：このカードが墓地へ送られた場合に発動できる。デッキから儀式モンスター１体または儀式魔法カード１枚を手札に加える。",
    image: "card100179270_1.jpg",
    hasDefense: true as const,
    hasLevel: true as const,
    hasLink: false as const,
    hasRank: false as const,
    canNormalSummon: false,
};
