export default {
    card_name: "セイクリッド・トレミスM7",
    card_type: "モンスター" as const,
    monster_type: "エクシーズモンスター" as const,
    rank: 6,
    element: "光" as const,
    race: "機械" as const,
    attack: 2700,
    defense: 2000,
    filterAvailableMaterials: () => true,
    materialCondition: () => true,
    text: "レベル６モンスター×２\nこのカードは「セイクリッド・トレミスM７」以外の自分フィールドの「セイクリッド」Xモンスターの上に重ねてX召喚する事もできる。この方法で特殊召喚したターン、このカードの①の効果は発動できない。①：１ターンに１度、このカードのX素材を１つ取り除き、自分または相手の、フィールド・墓地のモンスター１体を対象として発動できる。そのモンスターを持ち主の手札に戻す。",
    image: "card100287504_1.jpg",
    hasDefense: true as const,
    hasLevel: false as const,
    hasLink: false as const,
    hasRank: true as const,
    canNormalSummon: false,
};
